# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"  # Root-level workflows
    schedule:
      interval: "daily"
    labels:
      - update
  - package-ecosystem: "pip"
    directory: "/"  # Assumes requirements.txt in root
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    ignore:
      - dependency-name: "pip"
        versions: ["*"]
    labels:
      - update
