# SPDX-FileCopyrightText: 2025 Andreas Krüger
# SPDX-License-Identifier: MIT

name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: '🚀 Features'
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'

  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'

  - title: '📚 Documentation'
    labels:
      - 'docs'
      - 'documentation'

  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'style'
      - 'refactor'
      - 'perf'
      - 'build'
      - 'update'

  - title: '🧪 Tests'
    labels:
      - 'test'
      - 'tests'

  - title: '🚨 CI/CD'
    labels:
      - 'ci'
      - 'workflow'

  - title: '🔙 Reverts'
    labels:
      - 'revert'

  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feat'
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'docs'
      - 'style'
      - 'perf'
      - 'test'
      - 'ci'
      - 'security'
      - 'workflow'

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS

  Thanks to all the contributors who made this release possible. You rock!
