name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
      - 'fix'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
      - 'refactor'
      - 'docs'
  - title: '🔒 Security'
    labels:
      - 'security'
      - 'vulnerability'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'breaking'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'security'

template: |
  ## What's Changed

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
