# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Kruger

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: local
    hooks:
      - id: check-signed-commit
        name: Require signed commits
        entry: bash .hooks/require-gpg.sh
        language: script
        stages: [commit-msg]
