# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: Auto Label PRs from Conventional Commits

on:
  pull_request:
    branches: [main]
    types:
      [opened, reopened, labeled, unlabeled]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  label:
    name: Assign PR Labels
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: mauroalderete/action-assign-labels@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
