name: License Scan

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

jobs:
  license-scan:
    name: FOSS License Scan
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run License Scan
        uses: licensee/licensed-ci@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
