# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: FOSS License Scan

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 2 * * *'

permissions:
  contents: read
  pull-requests: write

jobs:
  license_check:
    name: FOSS License Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Run REUSE compliance check
        uses: fsfe/reuse-action@v5
