# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: Draft Release

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]

permissions:
  contents: read
  pull-requests: write

jobs:
  update_release_draft:
    name: Update Release Draft
    runs-on: ubuntu-latest

    steps:
      - name: Run Release Drafter
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
