# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'  # Trigger on semantic version tags like v1.0.0

permissions:
  contents: read
  pull-requests: write

jobs:
  release:
    name: Publish GitHub Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
