name: Trivy Security Scans

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC

jobs:
  sca-and-config:
    name: SCA & Misconfig Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SCA Scan (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH

      - name: Misconfiguration Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          format: table
          severity: CRITICAL,HIGH
