# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: Trivy SCA Scans

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'  # Runs daily at 01:00 UTC

permissions:
  contents: read
  pull-requests: write

jobs:
  sca-and-config:
    name: SCA Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: SCA Scan (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          ignore-unfixed: true
          format: table
          severity: CRITICAL,HIGH
