# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Andreas Krüger

name: Validate Branch Protection Config

on:
  pull_request:
    paths:
      - '.github/branch-protection.yml'

jobs:
  validate-yaml:
    name: Validate branch-protection.yml
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install yq (v4+)
        run: |
          wget https://github.com/mikefarah/yq/releases/download/v4.43.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Validate YAML structure
        run: |
          yq eval . .github/branch-protection.yml > /dev/null
